
baseurl = "http://stephenlw.com/"
theme = "hugo-stephenlw"
title = "Stephen Lane-Walsh"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

builddrafts = false
canonifyurls = true
paginate = 3
PaginatePath = "/"

[author]
    name = "Stephen Lane-Walsh"

[permalinks]
    page = "/:title/"
    post = "/article/:title/"

[params]
    title = "Stephen Lane-Walsh"
    subtitle = "Software Engineer, Server Administrator, Full-Stack Developer & Curious Hobbiest"
    description = "Stephen Lane-Walsh's Portfolio Site"
    author = "Stephen Lane-Walsh"

    menu = [
        ["/resume/",    "Resume"],
        ["/project/",   "Projects"],
        ["/post/",      "Blog"]
    ]
